import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { IonicModule, AlertController } from '@ionic/angular';
import { Subscription } from 'rxjs';
import { IplPaymentsService } from '../ipl-payments.service';
import { IplPeriodsService } from '../ipl-periods.service';
import { ResidentsService } from '../../residents/residents.service';
import { HouseUnitsService } from '../../house-units/house-units.service';
import {
  IplPayment,
  IplPeriod,
  CreateIplPaymentDto,
  IplPaymentMethod,
  IplPaymentStatus,
  IPL_PAYMENT_METHOD_LABELS
} from '../ipl-payments.model';
import { SelectOption } from '@shared/ui/form-controls/form.model';
import { Resident } from '../../residents/residents.model';
import { HouseUnit } from '../../house-units/house-units.model';

/**
 * Extended Resident type with house unit data for IPL calculations
 */
interface ResidentWithHouseUnit extends Resident {
  landArea?: number;
  iplPercentage?: number;
  houseUnit?: HouseUnit;
}
import { LoadingService } from '@services/loading.service';
import { ToastService } from '@services/toast.service';
import {
  FormDatePickerComponent,
  FormSelectComponent,
  FormInputComponent,
  FormTextareaComponent,
  FormButtonComponent
} from '@shared/ui/form-controls';

/**
 * IPL Payment Form Page
 * Create IPL payment input for coordinators
 */
@Component({
  selector: 'app-ipl-payment-form',
  standalone: true,
  imports: [
    CommonModule,
    IonicModule,
    ReactiveFormsModule,
    FormsModule,
    FormDatePickerComponent,
    FormSelectComponent,
    FormInputComponent,
    FormTextareaComponent,
    FormButtonComponent
  ],
  templateUrl: './ipl-payment-form.page.html'
})
export class IplPaymentFormPage implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private fb = inject(FormBuilder);
  private iplPaymentsService = inject(IplPaymentsService);
  private iplPeriodsService = inject(IplPeriodsService);
  private residentsService = inject(ResidentsService);
  private houseUnitsService = inject(HouseUnitsService);
  private loadingService = inject(LoadingService);
  private toastService = inject(ToastService);
  private alertController = inject(AlertController);

  form: FormGroup;
  payment: IplPayment | null = null;
  isEditMode = false;
  loading = false;
  loadingData = true;
  error: string | null = null;

  residents: Resident[] = [];
  periods: IplPeriod[] = [];
  houseUnits: HouseUnit[] = [];
  selectedResident: ResidentWithHouseUnit | null = null;
  selectedPeriod: IplPeriod | null = null;

  // File upload
  selectedFile: File | null = null;
  filePreview: string | null = null;

  // Payment methods
  readonly PAYMENT_METHODS = Object.values(IplPaymentMethod);

  private subscriptions: Subscription[] = [];

  constructor() {
    this.form = this.fb.group({
      periodId: ['', Validators.required],
      residentId: ['', Validators.required],
      monthCount: [1, [Validators.min(1), Validators.max(24)]],
      paymentDate: [this.formatDateForInput(new Date()), Validators.required],
      paymentMethod: [IplPaymentMethod.TRANSFER, Validators.required],
      kegiatanAmount: ['', [Validators.min(0)]],  // NEW: Iuran kegiatan warga (optional)
      notes: ['']
      // Note: referenceNumber is now auto-generated by backend
    });
  }

  ngOnInit(): void {
    this.loadData();
  }

  /**
   * Load dropdown data (periods, residents, and house units)
   */
  loadData(): void {
    // Load active periods only
    this.subscriptions.push(
      this.iplPeriodsService.getActive().subscribe({
        next: (periods) => {
          this.periods = periods;
          this.loadingData = false;
        },
        error: (error) => {
          this.error = 'Gagal memuat data periode';
          this.loadingData = false;
          console.error('Error loading periods:', error);
        }
      })
    );

    // Load residents (in real app, filter by coordinator's block)
    this.subscriptions.push(
      this.residentsService.getAll({ limit: 1000 }).subscribe({
        next: (residentsData) => {
          this.residents = residentsData.data;
        },
        error: (error) => {
          console.error('Error loading residents:', error);
        }
      })
    );

    // Load house units to get landArea and iplPercentage
    this.subscriptions.push(
      this.houseUnitsService.getAll({ limit: 1000 }).subscribe({
        next: (unitsData) => {
          this.houseUnits = unitsData.data;
        },
        error: (error) => {
          console.error('Error loading house units:', error);
        }
      })
    );
  }

  /**
   * Handle resident selection change
   */
  onResidentChange(): void {
    const residentId = this.form.get('residentId')?.value;
    const resident = this.residents.find(r => r.id === residentId);

    if (resident) {
      // Find the associated house unit for this resident
      const houseUnit = this.houseUnits.find(unit => unit.residents?.some(r => r.id === residentId));

      // Create an enriched resident object with house unit data
      this.selectedResident = {
        ...resident,
        landArea: houseUnit?.landArea,
        iplPercentage: houseUnit?.iplPercentage,
        houseUnit: houseUnit
      };
    } else {
      this.selectedResident = null;
    }
  }

  /**
   * Handle period selection change
   */
  onPeriodChange(): void {
    const periodId = this.form.get('periodId')?.value;
    const period = this.periods.find(p => p.id === periodId);

    if (period) {
      this.selectedPeriod = period;
    } else {
      this.selectedPeriod = null;
    }
  }

  /**
   * Handle file selection
   */
  onFileSelect(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];

      // Create preview for images
      if (this.selectedFile.type.startsWith('image/')) {
        const reader = new FileReader();
        reader.onload = (e) => {
          this.filePreview = e.target?.result as string;
        };
        reader.readAsDataURL(this.selectedFile);
      } else {
        this.filePreview = null;
      }
    }
  }

  /**
   * Remove selected file
   */
  removeFile(): void {
    this.selectedFile = null;
    this.filePreview = null;
    const fileInput = document.querySelector('input[type="file"]') as HTMLInputElement;
    if (fileInput) {
      fileInput.value = '';
    }
  }

  /**
   * Calculate IPL amount based on formula
   * Formula: landArea * baseRate * (iplPercentage / 100)
   */
  calculateIplAmount(): number {
    if (!this.selectedResident || !this.selectedPeriod) {
      return 0;
    }

    const landArea = this.selectedResident.landArea || this.selectedResident.houseUnit?.landArea || 0;
    const iplPercentage = this.selectedResident.iplPercentage || this.selectedResident.houseUnit?.iplPercentage || 100;
    const baseRate = this.selectedPeriod.baseRate || 2500;

    return (landArea * baseRate * (iplPercentage / 100));
  }

  /**
   * Get total amount for multi-month payment
   * Includes IPL amount and kegiatan amount (if any)
   */
  getTotalAmount(): number {
    const monthCount = this.form.get('monthCount')?.value || 1;
    const iplTotal = this.calculateIplAmount() * monthCount;
    const kegiatanAmount = this.form.get('kegiatanAmount')?.value || 0;
    return iplTotal + kegiatanAmount;
  }

  /**
   * Get kegiatan amount from form
   */
  getKegiatanAmount(): number {
    return this.form.get('kegiatanAmount')?.value || 0;
  }

  /**
   * Get selected month count
   */
  getMonthCount(): number {
    return this.form.get('monthCount')?.value || 1;
  }

  /**
   * Check if this is a multi-month payment
   */
  isMultiMonthPayment(): boolean {
    return this.getMonthCount() > 1;
  }

  /**
   * Increment month count
   */
  incrementMonthCount(): void {
    const current = this.getMonthCount();
    if (current < 24) {
      this.form.get('monthCount')?.setValue(current + 1);
    }
  }

  /**
   * Decrement month count
   */
  decrementMonthCount(): void {
    const current = this.getMonthCount();
    if (current > 1) {
      this.form.get('monthCount')?.setValue(current - 1);
    }
  }

  /**
   * Validate form
   */
  private validateForm(): { valid: boolean; error?: string } {
    if (!this.selectedFile) {
      return { valid: false, error: 'Bukti transfer wajib diupload' };
    }

    if (!this.selectedResident) {
      return { valid: false, error: 'Pilih warga terlebih dahulu' };
    }

    if (!this.selectedPeriod) {
      return { valid: false, error: 'Pilih periode IPL terlebih dahulu' };
    }

    // Validate file size (max 5MB)
    if (this.selectedFile && this.selectedFile.size > 5 * 1024 * 1024) {
      return { valid: false, error: 'Ukuran file maksimal 5MB' };
    }

    // Validate file type
    const allowedTypes = ['image/jpeg', 'image/png', 'image/jpg', 'application/pdf'];
    if (this.selectedFile && !allowedTypes.includes(this.selectedFile.type)) {
      return { valid: false, error: 'Format file harus JPG, PNG, atau PDF' };
    }

    return { valid: true };
  }

  /**
   * Submit form
   */
  async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.toastService.error('Mohon lengkapi semua field yang wajib diisi');
      return;
    }

    // Validate file and other conditions
    const validation = this.validateForm();
    if (!validation.valid) {
      this.toastService.error(validation.error || 'Validasi gagal');
      return;
    }

    const formValue = this.form.value;

    const dto: CreateIplPaymentDto = {
      periodId: formValue.periodId,
      residentId: formValue.residentId,
      monthCount: formValue.monthCount || 1,
      paymentDate: formValue.paymentDate,
      paymentMethod: formValue.paymentMethod,
      kegiatanAmount: formValue.kegiatanAmount || undefined,  // NEW: Iuran kegiatan warga
      notes: formValue.notes,
      proofFile: this.selectedFile || undefined
      // Note: referenceNumber is now auto-generated by backend
    };

    this.createPayment(dto);
  }

  /**
   * Create new payment
   */
  private async createPayment(dto: CreateIplPaymentDto): Promise<void> {
    this.loadingService.show({ message: 'Mengirim pembayaran...' });

    this.subscriptions.push(
      this.iplPaymentsService.create(dto).subscribe({
        next: async (result) => {
          this.loadingService.dismiss();
          if (result) {
            // Show success modal with reference number
            await this.showSuccessModal(result);
          }
        },
        error: (error) => {
          this.loadingService.dismiss();
          this.toastService.error('Gagal mengirim pembayaran');
          console.error('Create payment error:', error);
        }
      })
    );
  }

  /**
   * Show success modal with reference number and payment details
   */
  private async showSuccessModal(payment: IplPayment): Promise<void> {
    const isApproved = payment.status === IplPaymentStatus.APPROVED;
    const statusMessage = isApproved ? 'Pembayaran berhasil disetujui' : 'Pembayaran berhasil dikirim dan menunggu persetujuan';

    let message = `
      <div class="success-modal-content">
        <div class="reference-section">
          <p class="reference-label">Nomor Referensi:</p>
          <p class="reference-number">${payment.referenceNumber || '-'}</p>
        </div>
        <div class="payment-summary">
          <div class="summary-row">
            <span>Status:</span>
            <strong>${isApproved ? '✅ Disetujui' : '⏳ Menunggu Approval'}</strong>
          </div>
    `;

    // Add multi-month info if applicable
    if (payment._meta?.isMultiMonth) {
      message += `
          <div class="summary-row">
            <span>Jumlah Bulan:</span>
            <strong>${payment._meta.monthCount} bulan</strong>
          </div>
      `;
    }

    // Add kegiatan payment info if applicable
    if (payment.kegiatanPayment) {
      message += `
          <div class="summary-row">
            <span>Iuran Kegiatan:</span>
            <strong>${this.formatCurrency(payment.kegiatanPayment.amount)}</strong>
          </div>
      `;
    }

    // Add total amounts
    if (payment._meta?.grandTotal) {
      message += `
          <div class="summary-divider"></div>
          <div class="summary-row total">
            <span>Total Pembayaran:</span>
            <strong>${this.formatCurrency(payment._meta.grandTotal)}</strong>
          </div>
      `;
    } else {
      message += `
          <div class="summary-row total">
            <span>Total IPL:</span>
            <strong>${this.formatCurrency(payment.calculatedAmount)}</strong>
          </div>
      `;
    }

    message += `
        </div>
      </div>
    `;

    const alert = await this.alertController.create({
      header: '✅ Pembayaran Berhasil',
      message: message,
      cssClass: 'success-modal-alert',
      buttons: [
        {
          text: 'Tambah Lagi',
          role: 'cancel',
          handler: () => {
            // Reset form and stay on page
            this.form.reset();
            this.selectedFile = null;
            this.filePreview = null;
            this.selectedResident = null;
            this.selectedPeriod = null;
          }
        },
        {
          text: 'Lihat Detail',
          handler: () => {
            this.router.navigate(['/admin/ipl-payments', payment.id]);
          }
        }
      ]
    });

    await alert.present();
  }

  /**
   * Navigate back to list
   */
  navigateBack(): void {
    this.router.navigate(['/admin/ipl-payments']);
  }

  /**
   * Format date for input (YYYY-MM-DD)
   */
  private formatDateForInput(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  /**
   * Format currency for display
   */
  formatCurrency(amount: number): string {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0
    }).format(amount);
  }

  /**
   * Format file size
   */
  formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  }

  /**
   * Get form control
   */
  get control() {
    return this.form.controls;
  }

  /**
   * Check if control has error
   */
  hasError(controlName: string, errorType?: string): boolean {
    const control = this.form.get(controlName);
    if (!control) return false;
    if (errorType) {
      return control.hasError(errorType) && (control.dirty || control.touched);
    }
    return control.invalid && (control.dirty || control.touched);
  }

  /**
   * Get error message
   */
  getErrorMessage(controlName: string): string {
    const control = this.form.get(controlName);
    if (!control || !control.errors) return '';

    if (control.errors['required']) {
      return 'Field ini wajib diisi';
    }

    return 'Input tidak valid';
  }

  /**
   * Check if field is invalid (for standardized form components)
   */
  isFieldInvalid(controlName: string): boolean {
    const control = this.form.get(controlName);
    return control ? control.invalid && (control.dirty || control.touched) : false;
  }

  /**
   * Check if form is valid
   */
  isFormValid(): boolean {
    return this.form.valid && this.selectedFile !== null;
  }

  /**
   * Get submit button text
   */
  get submitButtonText(): string {
    return 'Kirim Pembayaran';
  }

  /**
   * Get page title
   */
  get pageTitle(): string {
    return 'Input Pembayaran IPL';
  }

  /**
   * Convert periods to select options
   */
  get periodOptions(): SelectOption[] {
    return this.periods.map(period => ({
      value: period.id,
      label: `${period.periodName} (${period.month}/${period.year})`
    }));
  }

  /**
   * Convert payment methods to select options
   */
  get paymentMethodOptions(): SelectOption[] {
    return this.PAYMENT_METHODS.map(method => ({
      value: method,
      label: IPL_PAYMENT_METHOD_LABELS[method] || method
    }));
  }

  /**
   * Convert residents to select options with unit info
   */
  get residentOptions(): SelectOption[] {
    return this.residents.map(r => {
      const houseUnit = this.houseUnits.find(unit => unit.residents?.some(res => res.id === r.id));
      const blockName = r.houseBlock?.blockName || '-';
      const unitNumber = r.unitNumber || '';
      return {
        value: r.id,
        label: `${r.firstName} ${r.lastName} - ${blockName} ${unitNumber}`
      };
    });
  }

  /**
   * Cleanup subscriptions
   */
  ngOnDestroy(): void {
    this.subscriptions.forEach((sub) => sub.unsubscribe());
  }
}
